//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inovatec.OfficeManagementTool.Localization.Resources.Equipment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_CA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_CA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inovatec.OfficeManagementTool.Localization.Resources.Equipment.en-CA", typeof(en_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Equipment.
        /// </summary>
        internal static string AddEquipment {
            get {
                return ResourceManager.GetString("AddEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Equipment.
        /// </summary>
        internal static string AssignedEquipment {
            get {
                return ResourceManager.GetString("AssignedEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Equipment.
        /// </summary>
        internal static string AssignEquipment {
            get {
                return ResourceManager.GetString("AssignEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign equipment..
        /// </summary>
        internal static string AssignEquipmentFail {
            get {
                return ResourceManager.GetString("AssignEquipmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment assigned successfully..
        /// </summary>
        internal static string AssignEquipmentSucc {
            get {
                return ResourceManager.GetString("AssignEquipmentSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an item..
        /// </summary>
        internal static string ChooseItem {
            get {
                return ResourceManager.GetString("ChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Equipment.
        /// </summary>
        internal static string DeleteEquipment {
            get {
                return ResourceManager.GetString("DeleteEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment added successfuly..
        /// </summary>
        internal static string EquipmentAddedSuccessfully {
            get {
                return ResourceManager.GetString("EquipmentAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete equipment.
        /// </summary>
        internal static string EquipmentDeleteConfirm {
            get {
                return ResourceManager.GetString("EquipmentDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete equipment..
        /// </summary>
        internal static string EquipmentDeleteFail {
            get {
                return ResourceManager.GetString("EquipmentDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment deleted successfully..
        /// </summary>
        internal static string EquipmentDeleteSucc {
            get {
                return ResourceManager.GetString("EquipmentDeleteSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment doesn&apos;t exist..
        /// </summary>
        internal static string EquipmentDoesntExist {
            get {
                return ResourceManager.GetString("EquipmentDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Evidentation.
        /// </summary>
        internal static string EquipmentEvidentation {
            get {
                return ResourceManager.GetString("EquipmentEvidentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment is null..
        /// </summary>
        internal static string EquipmentIsNull {
            get {
                return ResourceManager.GetString("EquipmentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment item code exists..
        /// </summary>
        internal static string EquipmentItemCodeExists {
            get {
                return ResourceManager.GetString("EquipmentItemCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add equipment..
        /// </summary>
        internal static string FailedEquipmentAdd {
            get {
                return ResourceManager.GetString("FailedEquipmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch equipment..
        /// </summary>
        internal static string FailedToFetchEquipment {
            get {
                return ResourceManager.GetString("FailedToFetchEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch items..
        /// </summary>
        internal static string FailedToFetchItems {
            get {
                return ResourceManager.GetString("FailedToFetchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch users..
        /// </summary>
        internal static string FailedToFetchUsers {
            get {
                return ResourceManager.GetString("FailedToFetchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code is required..
        /// </summary>
        internal static string ItemCodeRequired {
            get {
                return ResourceManager.GetString("ItemCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Equipment.
        /// </summary>
        internal static string SearchEquipment {
            get {
                return ResourceManager.GetString("SearchEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned Equipment.
        /// </summary>
        internal static string UnassignedEquipment {
            get {
                return ResourceManager.GetString("UnassignedEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign Equipment.
        /// </summary>
        internal static string UnassignEquipment {
            get {
                return ResourceManager.GetString("UnassignEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unassign equipment..
        /// </summary>
        internal static string UnassignEquipmentFail {
            get {
                return ResourceManager.GetString("UnassignEquipmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment unassigned successfully..
        /// </summary>
        internal static string UnassignEquipmentSucc {
            get {
                return ResourceManager.GetString("UnassignEquipmentSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
