//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inovatec.OfficeManagementTool.Localization.Resources.Equipment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sr_CA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sr_CA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inovatec.OfficeManagementTool.Localization.Resources.Equipment.sr-CA", typeof(sr_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Opremu.
        /// </summary>
        internal static string AddEquipment {
            get {
                return ResourceManager.GetString("AddEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodeljena Oprema.
        /// </summary>
        internal static string AssignedEquipment {
            get {
                return ResourceManager.GetString("AssignedEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodeli Opremu.
        /// </summary>
        internal static string AssignEquipment {
            get {
                return ResourceManager.GetString("AssignEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dodeljivanju opreme..
        /// </summary>
        internal static string AssignEquipmentFail {
            get {
                return ResourceManager.GetString("AssignEquipmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema je uspešno dodeljena..
        /// </summary>
        internal static string AssignEquipmentSucc {
            get {
                return ResourceManager.GetString("AssignEquipmentSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime Kategorije.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite proizvod..
        /// </summary>
        internal static string ChooseItem {
            get {
                return ResourceManager.GetString("ChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši Opremu.
        /// </summary>
        internal static string DeleteEquipment {
            get {
                return ResourceManager.GetString("DeleteEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema je uspešno dodata..
        /// </summary>
        internal static string EquipmentAddedSuccessfully {
            get {
                return ResourceManager.GetString("EquipmentAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite da izbrišete opremu.
        /// </summary>
        internal static string EquipmentDeleteConfirm {
            get {
                return ResourceManager.GetString("EquipmentDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri brisanju opreme..
        /// </summary>
        internal static string EquipmentDeleteFail {
            get {
                return ResourceManager.GetString("EquipmentDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema je uspešno izbrisana..
        /// </summary>
        internal static string EquipmentDeleteSucc {
            get {
                return ResourceManager.GetString("EquipmentDeleteSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema ne postoji..
        /// </summary>
        internal static string EquipmentDoesntExist {
            get {
                return ResourceManager.GetString("EquipmentDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidentiranje opreme.
        /// </summary>
        internal static string EquipmentEvidentation {
            get {
                return ResourceManager.GetString("EquipmentEvidentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema je null..
        /// </summary>
        internal static string EquipmentIsNull {
            get {
                return ResourceManager.GetString("EquipmentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema sa unetim šifrom proizvoda već postoji..
        /// </summary>
        internal static string EquipmentItemCodeExists {
            get {
                return ResourceManager.GetString("EquipmentItemCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dodavanju opreme..
        /// </summary>
        internal static string FailedEquipmentAdd {
            get {
                return ResourceManager.GetString("FailedEquipmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju opreme..
        /// </summary>
        internal static string FailedToFetchEquipment {
            get {
                return ResourceManager.GetString("FailedToFetchEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju proizvoda..
        /// </summary>
        internal static string FailedToFetchItems {
            get {
                return ResourceManager.GetString("FailedToFetchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju korisnika..
        /// </summary>
        internal static string FailedToFetchUsers {
            get {
                return ResourceManager.GetString("FailedToFetchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra Proizvoda.
        /// </summary>
        internal static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra proizvoda je obavezna..
        /// </summary>
        internal static string ItemCodeRequired {
            get {
                return ResourceManager.GetString("ItemCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv Proizvoda.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvodi.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži opremu.
        /// </summary>
        internal static string SearchEquipment {
            get {
                return ResourceManager.GetString("SearchEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedodeljena Oprema.
        /// </summary>
        internal static string UnassignedEquipment {
            get {
                return ResourceManager.GetString("UnassignedEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi dodelu opreme.
        /// </summary>
        internal static string UnassignEquipment {
            get {
                return ResourceManager.GetString("UnassignEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri poništavanju dodele opreme..
        /// </summary>
        internal static string UnassignEquipmentFail {
            get {
                return ResourceManager.GetString("UnassignEquipmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodela opreme je uspešno poništena..
        /// </summary>
        internal static string UnassignEquipmentSucc {
            get {
                return ResourceManager.GetString("UnassignEquipmentSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime Korisnika.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
