// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Item
    {
        public Item()
        {
            Equipment = new HashSet<Equipment>();
            OrderItems = new HashSet<OrderItem>();
            OrderRequests = new HashSet<OrderRequest>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long CategoryId { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
    }
}