// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Office
    {
        public Office()
        {
            OrderRequests = new HashSet<OrderRequest>();
            Orders = new HashSet<Order>();
            Reports = new HashSet<Report>();
            Schedulers = new HashSet<Scheduler>();
            Users = new HashSet<User>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }

        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<Scheduler> Schedulers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}