// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Order
    {
        public Order()
        {
            OrderAttachments = new HashSet<OrderAttachment>();
            OrderItems = new HashSet<OrderItem>();
        }

        public long Id { get; set; }
        public long OfficeId { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long State { get; set; }

        public virtual Office Office { get; set; }
        public virtual ICollection<OrderAttachment> OrderAttachments { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}