// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Report
    {
        public long Id { get; set; }
        public long OfficeId { get; set; }
        public long UserId { get; set; }
        public string Description { get; set; }
        public int State { get; set; }
        public long EquipmentId { get; set; }
        public int Category { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }

        public virtual Office Office { get; set; }
        public virtual User User { get; set; }
    }
}