// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class Scheduler
    {
        public long Id { get; set; }
        public long OfficeId { get; set; }
        public DateTime ScheduledFor { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }
        public bool Repetable { get; set; }

        public virtual Office Office { get; set; }
    }
}