// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inovatec.OfficeManagementTool.Models.Entity
{
    public partial class User
    {
        public User()
        {
            Equipment = new HashSet<Equipment>();
            OrderRequests = new HashSet<OrderRequest>();
            Reports = new HashSet<Report>();
        }

        public long Id { get; set; }
        public long OfficeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Role { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public long LastModifiedBy { get; set; }
        public string ResetPasswordToken { get; set; }
        public DateTime? ResetPasswordTokenExpirationTime { get; set; }

        public virtual Office Office { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}