IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND CONSTRAINT_NAME='FK_Equipment_User' AND TABLE_NAME='Equipment')
AND EXISTS (select 1 from INFORMATION_SCHEMA.COLUMNS Where COLUMN_NAME='UserId' AND TABLE_NAME='Equipment' AND TABLE_SCHEMA='dbo')
AND EXISTS (select 1 from INFORMATION_SCHEMA.COLUMNS Where COLUMN_NAME='Id' AND TABLE_NAME = 'User' AND TABLE_SCHEMA='dbo')
BEGIN
	ALTER TABLE Equipment
	ADD CONSTRAINT FK_Equipment_User FOREIGN KEY ([UserId]) REFERENCES [User](Id);
END