IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND CONSTRAINT_NAME='FK_OrderAttachment_Order' AND TABLE_NAME='OrderAttachment')
AND EXISTS (select 1 from INFORMATION_SCHEMA.COLUMNS Where COLUMN_NAME='OrderId' AND TABLE_NAME='OrderAttachment' AND TABLE_SCHEMA='dbo')
AND EXISTS (select 1 from INFORMATION_SCHEMA.COLUMNS Where COLUMN_NAME='Id' AND TABLE_NAME = 'Order' AND TABLE_SCHEMA='dbo')
BEGIN
	ALTER TABLE OrderAttachment
	ADD CONSTRAINT FK_OrderAttachment_Order FOREIGN KEY ([OrderId]) REFERENCES [Order]([Id]);
END
