IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND CONSTRAINT_NAME='FK_Order_Office' AND TABLE_NAME='Order')
AND EXISTS (select 1 from INFORMATION_SCHEMA.COLUMNS Where COLUMN_NAME='OfficeId' AND TABLE_NAME='OrderRequest' AND TABLE_SCHEMA='dbo')
AND EXISTS (select 1 from INFORMATION_SCHEMA.COLUMNS Where COLUMN_NAME='Id' AND TABLE_NAME = 'Office' AND TABLE_SCHEMA='dbo')
BEGIN
	ALTER TABLE [Order]
	ADD CONSTRAINT FK_Order_Office FOREIGN KEY ([OfficeId]) REFERENCES [Office]([Id]);
END
