//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inovatec.OfficeManagementTool.Localization.Resources.Items {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_CA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_CA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inovatec.OfficeManagementTool.Localization.Resources.Items.en-CA", typeof(en_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add item..
        /// </summary>
        internal static string AddItemFail {
            get {
                return ResourceManager.GetString("AddItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added successfully..
        /// </summary>
        internal static string AddItemSucc {
            get {
                return ResourceManager.GetString("AddItemSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string DeleteItemConfirmDialog {
            get {
                return ResourceManager.GetString("DeleteItemConfirmDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete item..
        /// </summary>
        internal static string DeleteItemFail {
            get {
                return ResourceManager.GetString("DeleteItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item deleted successfully..
        /// </summary>
        internal static string DeleteItemSucc {
            get {
                return ResourceManager.GetString("DeleteItemSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch categories..
        /// </summary>
        internal static string FailedToFetch {
            get {
                return ResourceManager.GetString("FailedToFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch items..
        /// </summary>
        internal static string FailedToFetchItems {
            get {
                return ResourceManager.GetString("FailedToFetchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Items.
        /// </summary>
        internal static string SearchItems {
            get {
                return ResourceManager.GetString("SearchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Item.
        /// </summary>
        internal static string UpdateItem {
            get {
                return ResourceManager.GetString("UpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update item..
        /// </summary>
        internal static string UpdateItemFail {
            get {
                return ResourceManager.GetString("UpdateItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item updated successfully..
        /// </summary>
        internal static string UpdateItemSucc {
            get {
                return ResourceManager.GetString("UpdateItemSucc", resourceCulture);
            }
        }
    }
}
