//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inovatec.OfficeManagementTool.Localization.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sr_CA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sr_CA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inovatec.OfficeManagementTool.Localization.Resources.Reports.sr-CA", typeof(sr_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcije.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve prijave.
        /// </summary>
        internal static string AllReports {
            get {
                return ResourceManager.GetString("AllReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkazano.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi kategoriju.
        /// </summary>
        internal static string CategorySelect {
            get {
                return ResourceManager.GetString("CategorySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oštećen.
        /// </summary>
        internal static string Damaged {
            get {
                return ResourceManager.GetString("Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum prijave.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis problema je obavezan.
        /// </summary>
        internal static string DescriptionEmptyErr {
            get {
                return ResourceManager.GetString("DescriptionEmptyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završeno.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radi sa kvarom.
        /// </summary>
        internal static string HasIssues {
            get {
                return ResourceManager.GetString("HasIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U toku.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedostaje.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje prijave.
        /// </summary>
        internal static string MyReports {
            get {
                return ResourceManager.GetString("MyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne radi.
        /// </summary>
        internal static string NotWorking {
            get {
                return ResourceManager.GetString("NotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostalo.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlasnik.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na čekanju.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi problem.
        /// </summary>
        internal static string ReportPrompt {
            get {
                return ResourceManager.GetString("ReportPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi status.
        /// </summary>
        internal static string StateSelect {
            get {
                return ResourceManager.GetString("StateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
