//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inovatec.OfficeManagementTool.Localization.Resources.Offices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_CA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_CA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inovatec.OfficeManagementTool.Localization.Resources.Offices.en-CA", typeof(en_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Office.
        /// </summary>
        internal static string AddOffice {
            get {
                return ResourceManager.GetString("AddOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete office.
        /// </summary>
        internal static string DeleteOffice {
            get {
                return ResourceManager.GetString("DeleteOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add office..
        /// </summary>
        internal static string FailedOfficeAdd {
            get {
                return ResourceManager.GetString("FailedOfficeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch offices..
        /// </summary>
        internal static string FailedToFetchOffices {
            get {
                return ResourceManager.GetString("FailedToFetchOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office added successfully..
        /// </summary>
        internal static string OfficeAddedSuccessfully {
            get {
                return ResourceManager.GetString("OfficeAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Administration.
        /// </summary>
        internal static string OfficeAdmin {
            get {
                return ResourceManager.GetString("OfficeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete office.
        /// </summary>
        internal static string OfficeDeleteConfirm {
            get {
                return ResourceManager.GetString("OfficeDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete office..
        /// </summary>
        internal static string OfficeDeleteFail {
            get {
                return ResourceManager.GetString("OfficeDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office deleted successfully..
        /// </summary>
        internal static string OfficeDeleteSucc {
            get {
                return ResourceManager.GetString("OfficeDeleteSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office doesn&apos;t exist..
        /// </summary>
        internal static string OfficeDoesntExist {
            get {
                return ResourceManager.GetString("OfficeDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office is null..
        /// </summary>
        internal static string OfficeIsNull {
            get {
                return ResourceManager.GetString("OfficeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office with this name already exists..
        /// </summary>
        internal static string OfficeNameExists {
            get {
                return ResourceManager.GetString("OfficeNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Office.
        /// </summary>
        internal static string UpdateOffice {
            get {
                return ResourceManager.GetString("UpdateOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update office..
        /// </summary>
        internal static string UpdateOfficeFail {
            get {
                return ResourceManager.GetString("UpdateOfficeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office updated successfully..
        /// </summary>
        internal static string UpdateOfficeSucc {
            get {
                return ResourceManager.GetString("UpdateOfficeSucc", resourceCulture);
            }
        }
    }
}
