// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Inovatec.OfficeManagementTool.Models.Entity;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Inovatec.OfficeManagementTool.ImplementationsDAL.Context
{
    public partial interface IOfficeManagementTool_IS2023_team2ContextProcedures
    {
        Task<int> CreateOrderAsync(long? officeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
